rewrite_rules = [
    ({"pos": "adj"}, "adj"),
    ({"pos": "adj", "sxfx": ["CP"]}, "adj"),
    ({"pos": "adj", "sxfx": ["SP"]}, "adj"),
    ({"pos": "adj", "subPos": ["n"] }, "adj"),
    ({"pos": "adj", "subPos": ["v"] }, "adj"),
    ({"pos": "adj", "sfx": ["CP"]}, "adj"),
    ({"pos": "adj", "sfx": ["SP"]}, "adj"),
    ({"pos": "adv"}, "adv"),
    ({"pos": "adv", "sxfx": ["CP"]}, "adv"),
    ({"pos": "adv", "sxfx": ["SP"]}, "adv"),
    ({"pos": "adv", "subPos": ["adj"] }, "adv"),
    ({"pos": "adv", "subPos": ["int"] }, "adv"),
    ({"pos": "adv", "subPos": ["wh"] }, "adv"),
    ({"pos": "aux", "stem": "be"}, "aux"),
    ({"pos": "aux", "stem": "do"}, "aux"),
    ({"pos": "aux", "stem": "have"}, "aux"),
    ({"pos": "fam"}, "chi"),
    ({"pos": "conj", "subPos": ["coo"] }, "coo"),
    ({"pos": "v", "subPos": ["cop"] , "sxfx": ["1S"]}, "cop"),
    ({"pos": "v", "subPos": ["cop"] , "sxfx": ["PRES"]}, "cop"),
    ({"pos": "v", "subPos": ["cop"] , "sxfx": ["3S"]}, "cop"),
    ({"pos": "v", "subPos": ["cop"] , "sxfx": ["PAST"], "sxfx": ["13S"]}, "cop"),
    ({"pos": "v", "subPos": ["cop"] , "sxfx": ["PAST"]}, "cop"),
    ({"pos": "v", "subPos": ["cop"] }, "cop"),
    ({"pos": "det", "subPos": ["num"] }, "det"),
    ({"pos": "det", "subPos": ["wh"] }, "det"),
    ({"pos": "pro", "subPos": ["pos", "det"] }, "det"),
    ({"pos": "det", "subPos": ["num"] , "sfx": ["PL"]}, "det-pl"),
    ({"pos": "pro", "subPos": ["exist"] }, "ext"),
    ({"pos": "n", "subPos": ["gerund"], "sfx": ["GERUND"]}, "ger"),
    ({"pos": "n", "subPos": ["gerund"], "sfx": ["GERUND", "PL"]}, "ger-pl"),
    ({"pos": "pro", "subPos": ["indef"] }, "idf"),
    ({"pos": "pro", "subPos": ["indef"] , "sfx": ["PL"]}, "idf"),
    ({"pos": "co"}, "int"),
    ({"pos": "co", "subPos": ["voc"] }, "int"),
    ({"pos": "n", "subPos": ["let"] }, "let"),
    ({"pos": "n", "subPos": ["let"] , "sfx": ["PL"]}, "let-pl"),
    ({"pos": "adv", "subPos": ["loc"] }, "loc"),
    ({"pos": "aux"}, "mod"),
    ({"pos": "n", "subPos": ["adj"] }, "n"),
    ({"pos": "n", "subPos": ["adj"] , "sfx": ["DIM"]}, "n"),
    ({"pos": "n", "subPos": ["adj"] , "sfx": ["NESS"]}, "n"),
    ({"pos": "n", "subPos": "v", "sfx": "AGT"}, "n"),
    ({"pos": "n", "sfx": ["DIM"]}, "n"),
    ({"pos": "n", "sfx": ["FULL"]}, "n"),
    ({"pos": "n", "sxfx": ["PL"]}, "n-pl"),
    ({"pos": "n", "subPos": ["pt"] }, "n-pl"),
    ({"pos": "n", "subPos": "v", "sfx": ["PL", "AGT"]}, "n-pl"),
    ({"pos": "n", "subPos": "dim", "sfx": ["PL"]}, "n-pl"),
    ({"pos": "n", "sfx": ["PL"]}, "n-pl"),
    ({"pos": "n", "sfx": ["PL"]}, "n-pl"),
    ({"pos": "n", "subPos": ["prop"] }, "n-pr"),
    ({"pos": "n", "subPos": ["prop"] , "sfx": ["POSS"]}, "n-pr"),
    ({"pos": "n", "subPos": ["prop"] , "sfx": ["PL"]}, "n-pr-pl"),
    ({"pos": "on"}, "ono"),
    ({"pos": "phon"}, "pho"),
    ({"pos": "pro", "subPos": ["poss"] }, "pps"),
    ({"pos": "prep"}, "pre"),
    ({"pos": "pro", "subPos": ["dem"] }, "pro"),
    ({"pos": "pro", "subPos": ["wh"] }, "pro"),
    ({"pos": "part"}, "prt"),
    ({"pos": "part", "sxfx": ["PERF"]}, "prt-pf"),
    ({"pos": "part", "sfx": ["PERF"]}, "prt-pf"),
    ({"pos": "part", "sfx": ["PROG"]}, "prt-pg"),
    ({"pos": "post"}, "psq"),
    ({"pos": "qn"}, "qnt"),
    ({"pos": "pro", "subPos": ["refl"] }, "ref"),
    ({"pos": "chi"}, "chi"),
    ({"pos": "det"}, "det"),
    ({"pos": "fil"}, "fil"),
    ({"pos": "inf"}, "inf"),
    ({"pos": "int"}, "int"),
    ({"pos": "n"}, "n"),
    ({"pos": "neg"}, "neg"),
    ({"pos": "neo"}, "dashNEO"),
    ({"pos": "pro"}, "pro"),
    ({"pos": ""}, "ptl"),
    ({"pos": "rel"}, "rel"),
    ({"pos": "unk"}, "unk"),
    ({"pos": "sing"}, "sin"),
    ({"pos": "conj", "subPos": ["subor"] }, "sub"),
    ({"pos": "adv", "subPos": "tem"}, "tem"),
    ({"pos": "bab"}, "vb"),
    ({"pos": "v"}, "vb"),
    ({"pos": "v", "subPos": ["n"] }, "vb"),
    ({"pos": "v", "sxfx": ["PAST"]}, "vbd"),
    ({"pos": "v", "sfx": ["PAST"]}, "vbd"),
    ({"pos": "v", "sxfx": ["ZERO"]}, "vbo"),
    ({"pos": "v", "sxfx": ["3S"]}, "vbs"),
    ({"pos": "v", "sfx": ["3S"]}, "vbs"),
    ({"pos": "wplay"}, "wpl"),
    ({"pos": "conj", "subPos": ["sub"]}, "sub"),
    ({"pos": "mod"}, "mod"),
    ({"pos": "mod", "stem": "do"}, "aux"),
    ({"pos": "test"}, "test"),
    ({"pos": "poss"}, "pos")
    ]
